folder_path = {
    "zip": "Compressed\Zip Files",
    "tar": "Compressed\Tar Files",
    "tgz": "Compressed\Tar Files",
    "bz2": "Compressed\bzip2",
    "rar": "Compressed\Rar Files",
    "mp3": "Audio",
    "m4a": "Audio",
    "mkv": "Video\MKV Files",
    "mp4": "Video\MP4 Files",
    "avi": "Video\Avi Files",
    "wma": "Video\WAV Files",
    "pdf": "Documents\PDF Files",
    "docx": "Documents\Word Files",
    "txt": "Documents\Text Files",
    "ini": "Documents\Ini Files",
    "xlsx": "Documents\Excel Files",
    "xls": "Documents\Excel Files",
    "xml": "Documents\XML Files",
    "html": "Documents\HTML Files",
    "jpg": "Pictures\JPG Files",
    "jpeg": "Pictures\JPEG Files",
    "png": "Pictures\PNG Files",
    "tif": "Pictures\TIFF Files",
    "svg": "Pictures\SVG Files",
    "exe": "Installers\exe Files",
    "msi": "Installers\msi Files",
}
